services:
  - type: web
    name: attract-backend
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: MONGO_URI
        scope: build
      - key: RAZORPAY_KEY_ID
        scope: build
      - key: RAZORPAY_KEY_SECRET
        scope: build
      - key: GEMINI_API_KEY
        scope: build
      - key: GEMINI_MODEL
        scope: build
      - key: OPENAI_API_KEY
        scope: build
      - key: PORT
        value: "5000"
