services:
  - type: web
    name: attract-backend
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGO_URI
        scope: build
      - key: RAZORPAY_KEY_ID
        scope: build
      - key: RAZORPAY_KEY_SECRET
        scope: build
      - key: GROQ_API_KEY
        scope: build
      - key: GROQ_MODEL
        scope: build
      - key: PORT
        value: "5000"
